name: test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'dist/**'
      - 'src/**'
      - 'package.json'
  push:
    branches:
      - main
    paths:
      - 'dist/**'
      - 'src/**'
      - 'package.json'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Static tests
        run: yarn run all
